import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import DynamicTabs from '../components/common/dynamic-tabs';
import CartSection from '../components/common/cart-section';
import { Box, Grid, Typography } from '@mui/material';
import NavBar from '../components/navbar';
import { footerSection } from '../components/common';
import { productName, tabsData, images } from '../utils/mock-data';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Grid container spacing={2} px={'71px'} mt={10}>
        <Grid item xs={4}>
          <div style={{ position: 'sticky', top: '100px', zIndex: 1 }}>
            <DynamicTabs tabs={tabsData} />
          </div>
        </Grid>
        <Grid item xs={4} sx={{ width: '200px' }}>
          {images.map((image, index) => (
            <img key={index} src={image.src} alt={image.alt} width={image.width} />
          ))}
        </Grid>
        <Grid item xs={4}>
          <div style={{ position: 'sticky', top: '100px', zIndex: 1 }}>
            <CartSection />
          </div>
        </Grid>
      </Grid>
      <div className={footerSection}>
        <div className="product">ViEW MOR PRODUCT LIKE THIS</div>
        <div style={{ display: 'flex', justifyContent: 'center' }}>
          {productName?.map((data, index) => (
            <div className="products-name" key={`${index}`}>
              {data}
            </div>
          ))}
        </div>
        <div className="author-note">
          <div className="note">A note from Author</div>
          <div className="note-description">
            The Forte Lurex Linen Viscose Jacket in Mother of Pearl features lunar lavishness by
            night and by day: a blazer in a linen blend shot with lurex for a shimmering surface
            that shines like a star in the sky.
          </div>
          <div className="author">--By MINNA SHIM, Fashion Editor</div>
        </div>
      </div>
    </div>
  );
}
